<a href="https://colab.research.google.com/github/ronish645/Ronish380/blob/main/Lecture4_ronish(19707).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def create_array_from_list(input_list):
    rows = []

    for element in input_list:
        row = [element + i for i in range(3)]
        rows.append(row)

    result_array = np.array(rows)

    return result_array

input_string = input("Enter a list of numbers separated by spaces or commas: ")

input_list = input_string.replace(',', ' ').split()

# Convert the elements to integers
input_list = [int(x) for x in input_list]

# Create the numpy array
output_array = create_array_from_list(input_list)

print(output_array)


Enter a list of numbers separated by spaces or commas: 2,4,6
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [2]:
import numpy as np

# Task 1
array1 = np.zeros(10, dtype=int)
print("Array filled with 0s:")
print(array1)

# Task 2
array2 = np.ones((3, 5), dtype=float)
print("\n3x5 array filled with 1s:")
print(array2)

# Task 3
array3 = np.full((3, 5), 3.14)
print("\n3x5 array filled with 3.14:")
print(array3)

# Task 4
array4 = np.arange(0, 21, 2)
print("\nLinear sequence array:")
print(array4)

# Task 5
array5 = np.linspace(0, 1, 5)
print("\nArray with values evenly spaced between 0 and 1:")
print(array5)

# Task 6
array6 = np.random.rand(3, 3)
print("\n3x3 array of uniformly distributed pseudorandom values between 0 and 1:")
print(array6)

# Task 7
array7 = np.random.randn(3, 3)
print("\n3x3 array of normally distributed pseudorandom values with mean 0 and standard deviation 1:")
print(array7)

# Task 8
array8 = np.random.randint(0, 10, (3, 3))
print("\n3x3 array of pseudorandom integers in the interval [0, 10):")
print(array8)

# Task 9
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# Task 10
x2 = np.array([[12, 1, 3, 7], [4, 0, 2, 3], [0, 0, 6, 9]])
new_array = x2[:2, :2]
new_array[0, 0] = 100
print("\nModified new_array:")
print(new_array)
print("\nOriginal x2 array:")
print(x2)

# Task 11
x2_copy = x2[:, :].copy()
x2_copy[0, 0] = 100
print("\nModified x2_copy:")
print(x2_copy)
print("\nOriginal x2 array (unchanged):")
print(x2)


Array filled with 0s:
[0 0 0 0 0 0 0 0 0 0]

3x5 array filled with 1s:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

3x5 array filled with 3.14:
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

Linear sequence array:
[ 0  2  4  6  8 10 12 14 16 18 20]

Array with values evenly spaced between 0 and 1:
[0.   0.25 0.5  0.75 1.  ]

3x3 array of uniformly distributed pseudorandom values between 0 and 1:
[[0.68613341 0.6752727  0.68671457]
 [0.01497611 0.96117101 0.73169479]
 [0.42814585 0.38035448 0.86855616]]

3x3 array of normally distributed pseudorandom values with mean 0 and standard deviation 1:
[[-0.63703488 -0.11178588  1.19596477]
 [ 0.91592207  0.55094288 -2.07716851]
 [ 0.21706613 -0.60977116 -1.26304404]]

3x3 array of pseudorandom integers in the interval [0, 10):
[[0 3 6]
 [6 3 5]
 [7 3 0]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Modified new_array:
[[100   1]
 [  4   0]]

Original x2 array:
[[100   1   3   7]
